[package]
name = "faasle-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
num-traits = "0.2.19"

[dev-dependencies]
ndarray = { version = "0.16.1", features = ["approx"] }
ndarray-rand = "0.15.0"
paste = "1.0.15"
