# This rustfmt file is added for configuration, but in practice much of our
# code is hand-formatted, frequently with more readable results.
# taken from rust-random/rand

# Comments:
normalize_comments = true
wrap_comments = false
comment_width = 90        # small excess is okay but prefer 80

# Arguments:
use_small_heuristics = "Default"
# TODO: single line functions only where short, please?
# https://github.com/rust-lang/rustfmt/issues/3358
fn_single_line = false

# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20

# Compatibility:
edition = "2021"

# Misc:
blank_lines_upper_bound = 2
reorder_impl_items = true
# report_todo = "Unnumbered"
# report_fixme = "Unnumbered"

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Imports:
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Ignored files:
ignore = []
